import { NAME } from './constants';

export const LOAD_WEB3_START = `${NAME}/LOAD_WEB3_START`;
export const LOAD_WEB3_SUCCESS = `${NAME}/LOAD_WEB3_SUCCESS`;
export const LOAD_WEB3_ERROR = `${NAME}/LOAD_WEB3_ERROR`;

export const GET_BLOCK_HEIGHT_START = `${NAME}/GET_BLOCK_HEIGHT_START`;
export const GET_BLOCK_HEIGHT_SUCCESS = `${NAME}/GET_BLOCK_HEIGHT_SUCCESS`;
export const GET_BLOCK_HEIGHT_ERROR = `${NAME}/GET_BLOCK_HEIGHT_ERROR`;

export const LOG_OUT = `${NAME}/LOG_OUT`;
